[package]
name = "crust"
version = "0.1.0"
authors = ["Carl Patenaude-Poulin <carl.patenaudepoulin@mail.mcgill.ca>", "Scott Cooper <scott.cooper2@mail.mcgill.ca"]

[dependencies]
rlibc = "*"

[dependencies.mm]
path = "./mm"


